export function cleanMathText(text: string): string {
  if (!text) return text;

  let cleaned = text
    .replace(/\\left\|/g, "|")
    .replace(/\\right\|/g, "|")
    .replace(/\\left\[/g, "[")
    .replace(/\\right\]/g, "]")
    .replace(/\\left\(/g, "(")
    .replace(/\\right\)/g, ")")
    .replace(/\\left\{/g, "{")
    .replace(/\\right\}/g, "}")
    .replace(/\\sum_\{([^}]*)\}\^\{([^}]*)\}/g, "Sum from $1 to $2 of")
    .replace(/\\sum/g, "Sum")
    .replace(/\\int_\{([^}]*)\}\^\{([^}]*)\}/g, "Integral from $1 to $2 of")
    .replace(/\\int/g, "Integral")
    .replace(/\\frac\{([^}]*)\}\{([^}]*)\}/g, "($1)/($2)")
    .replace(/\\sqrt\{([^}]*)\}/g, "sqrt($1)")
    .replace(/\\sqrt\[([^\]]*)\]\{([^}]*)\}/g, "$1th root of $2")
    .replace(/\\pi/g, "pi")
    .replace(/\\theta/g, "theta")
    .replace(/\\alpha/g, "alpha")
    .replace(/\\beta/g, "beta")
    .replace(/\\gamma/g, "gamma")
    .replace(/\\delta/g, "delta")
    .replace(/\\omega/g, "omega")
    .replace(/\\epsilon/g, "epsilon")
    .replace(/\\lambda/g, "lambda")
    .replace(/\\mu/g, "mu")
    .replace(/\\sigma/g, "sigma")
    .replace(/\\phi/g, "phi")
    .replace(/\\psi/g, "psi")
    .replace(/\\rho/g, "rho")
    .replace(/\\tau/g, "tau")
    .replace(/\\nu/g, "nu")
    .replace(/\\eta/g, "eta")
    .replace(/\\zeta/g, "zeta")
    .replace(/\\cdot/g, " * ")
    .replace(/\\times/g, " x ")
    .replace(/\\div/g, " / ")
    .replace(/\\pm/g, " +/- ")
    .replace(/\\mp/g, " -/+ ")
    .replace(/\\leq/g, " <= ")
    .replace(/\\geq/g, " >= ")
    .replace(/\\neq/g, " != ")
    .replace(/\\approx/g, " ~ ")
    .replace(/\\infty/g, "infinity")
    .replace(/\\partial/g, "d")
    .replace(/\\nabla/g, "del")
    .replace(/\\sin/g, "sin")
    .replace(/\\cos/g, "cos")
    .replace(/\\tan/g, "tan")
    .replace(/\\log/g, "log")
    .replace(/\\ln/g, "ln")
    .replace(/\\exp/g, "exp")
    .replace(/\\lim/g, "lim")
    .replace(/\\vec\{([^}]*)\}/g, "vector $1")
    .replace(/\^\{([^}]*)\}/g, "^($1)")
    .replace(/_\{([^}]*)\}/g, "_($1)")
    .replace(/\^(\d)/g, "^$1")
    .replace(/_(\d)/g, "_$1")
    .replace(/\\text\{([^}]*)\}/g, "$1")
    .replace(/\\mathrm\{([^}]*)\}/g, "$1")
    .replace(/\\mathbf\{([^}]*)\}/g, "$1")
    .replace(/\\[a-zA-Z]+/g, "")
    .replace(/\s+/g, " ")
    .trim();

  return cleaned;
}
